### PR TITLE
prevent cursor from changing it's position

### PR DESCRIPTION
**Pull request by bounceme**
cursor movement

### CODE REVIEW

**Comment by zweifisch** [comment]
Hi, restore cursor position looks interesting, could you please amend the commit? The var thing is fixed in e4675c82c93f6ac21682bbc63fb6ca2e151a81b0.

**Comment by bounceme** [comment]
I can still reproduce the var issue,try evaluating this line:
```
var i = 0;
```
my attempt was working, though it didn't include the let and const keywords

**Comment by zweifisch** [comment]
I've only tested it on linux. Which os do you use?

**Comment by bounceme** [comment]
i use OS X, the node version is 5.9.0
here's the error
```
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#     /private/tmp/repl.javascript.eval:8
#     console.log(var i = 0);
#                 ^^^
#     
#     SyntaxError: Unexpected token var
#         at exports.runInThisContext (vm.js:53:16)
#         at Module._compile (module.js:387:25)
#         at Object.Module._extensions..js (module.js:422:10)
#         at Module.load (module.js:357:32)
#         at Function.Module._load (module.js:314:12)
#         at Function.Module.runMain (module.js:447:10)
#         at startup (node.js:142:18)
#         at node.js:939:3
# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Comment by bounceme** [comment]
I think this is an OS X bundled sed issue, with gnu-sed from home-brew this works.I also tested in ubuntu   and couldn't reproduce.

**Pull request merged**
